/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/views/about/AboutPage.vue')['default']
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    Dashboard: typeof import('./src/views/Dashboard.vue')['default']
    DashboardPage: typeof import('./src/views/dashboard/DashboardPage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/ui/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/ui/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/ui/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/ui/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/ui/IconTooling.vue')['default']
    LoginPage: typeof import('./src/views/auth/LoginPage.vue')['default']
    LoginView: typeof import('./src/views/LoginView.vue')['default']
    NotFoundPage: typeof import('./src/views/not-found/NotFoundPage.vue')['default']
    NotFoundView: typeof import('./src/views/NotFoundView.vue')['default']
    OrderFormDialog: typeof import('./src/components/OrderFormDialog.vue')['default']
    OrderListPage: typeof import('./src/views/order-management/OrderListPage.vue')['default']
    OrderStatusBadge: typeof import('./src/components/domain/OrderStatusBadge.vue')['default']
    OrderView: typeof import('./src/views/OrderView.vue')['default']
    ProductFormDialog: typeof import('./src/components/ProductFormDialog.vue')['default']
    ProductListPage: typeof import('./src/views/product-management/ProductListPage.vue')['default']
    ProductsView: typeof import('./src/views/ProductsView.vue')['default']
    RoleListPage: typeof import('./src/views/role-management/RoleListPage.vue')['default']
    RolesView: typeof import('./src/views/RolesView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserFormDialog: typeof import('./src/components/UserFormDialog.vue')['default']
    UserListPage: typeof import('./src/views/user-management/UserListPage.vue')['default']
    UsersView: typeof import('./src/views/UsersView.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
